version: "3.9"
services:
  web:
    build: .
    container_name: ms-product
    ports:
      - 8000:8000
  wiremock:
    image: wiremock/wiremock:2.33.2
    container_name: wiremock
    ports:
      - 8080
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings

